services:
  dkdc-dev:
    build: .
    ports:
      - "1313:1313"
    working_dir: /app/websites/dkdc.dev
    command: zola serve --interface 0.0.0.0 --port 1313
  dkdc-io:
    build: .
    ports:
      - "1314:1314"
    working_dir: /app/websites/dkdc.io
    command: zola serve --interface 0.0.0.0 --port 1314
  app1:
    build: .
    ports:
      - "3007:3007"
    working_dir: /app/apps
    command: uv run panel serve app1.py --port 3007 --allow-websocket-origin=*
