[project]
name = "dkdc"
version = "0.30.0"
description = "don't know, don't care"
readme = "README.md"
authors = [{ name = "Cody", email = "cody@dkdc.dev" }]
requires-python = ">=3.12"
dependencies = ["dkdc-config", "dkdc-dl", "dkdc-fe", "dkdc-sh"]

[project.scripts]
dkdc = "dkdc:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
dkdc-config = { workspace = true }
dkdc-dl = { workspace = true }
dkdc-fe = { workspace = true }
dkdc-sh = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]
