[project]
name = "dkdc"
version = "0.30.0"
description = "don't know, don't care"
readme = "README.md"
authors = [{ name = "Cody", email = "cody@dkdc.dev" }]
requires-python = ">=3.12"
dependencies = ["panel>=1.7.0", "watchfiles>=1.0.5", "dkdc-dl"]

[project.scripts]
dkdc = "dkdc:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
dkdc-dl = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

# [[tool.uv.index]]
# url = "https://pypi.org/simple/"
# default = true

#[[tool.uv.index]]
#url = "https://us-python.pkg.dev/ascend-io-ops-artifacts/private-pypi/simple/"
