[package]
name = "dkdc-lake"
version = "0.1.0"
edition = "2021"

[dependencies]
duckdb = { version = "1.1", features = ["bundled"] }
dkdc-config = { path = "../dkdc-config" }
anyhow = "1.0"
chrono = "0.4"

[dev-dependencies]
