channels:
- conda-forge
- pytorch
dependencies:
- python=3.6.2
- pip:
  - azureml-train-automl
  - azureml-explain-model
  - azureml-dataprep==1.1.12
  - pytorch-transformers==1.0.0
  - inference-schema
- numpy
- py-xgboost<=0.80
- pytorch=1.1.0
- cudatoolkit=9.0
- conda-forge::fbprophet
name: azureml_1d010b4c21466997abb0fbdc22bafaf6
