[project]
name = "dkdc-fe"
version = "0.1.0"
description = "dkdc frontend dependencies"
readme = "README.md"
authors = [{ name = "Cody", email = "cody@dkdc.dev" }]
requires-python = ">=3.12"
dependencies = [
    "panel>=1.7.0",
    "watchfiles>=1.0.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"