name: project_environment
channels:
- defaults
dependencies:
- python=3.6.8
- pip:
  - --extra-index-url=https://test.pypi.org/simple
  - alghost==0.0.82
  - https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
  - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz#egg=en_core_web_sm
  - pillow==5.2.0
  - spacy==2.1.7
  - torchvision==0.2.2.post3